AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DatabaseUsername:
    NoEcho: true
    Type: String
  DatabasePassword:
    NoEcho: true
    Type: String
  DatabaseName:
    Type: String
    Default: mydb

Resources:
  PostgresDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 100
      DBInstanceClass: db.t2.micro
      DBName: !Ref DatabaseName
      Engine: postgres
      Iops: 1000
      MasterUsername: !Ref DatabaseUsername
      MasterUserPassword: !Ref DatabasePassword
      PubliclyAccessible: true

Outputs:
  DatabaseConnectionString:
    Value:
      Fn::Join:
        - ""
        -
          - "postgres://"
          - !Ref DatabaseUsername
          - ":"
          - !Ref DatabasePassword
          - "@"
          - !GetAtt [ PostgresDatabase, Endpoint.Address ]
          - "/"
          - !Ref DatabaseName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DBConnectionString"
