AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  DatabaseConnectionString:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-DBConnectionString
    Value:
      Fn::Join:
      - ''
      - - postgres://
        - Ref: DatabaseUsername
        - ':'
        - Ref: DatabasePassword
        - '@'
        - Fn::GetAtt:
          - PostgresDatabase
          - Endpoint.Address
        - /
        - Ref: DatabaseName
Parameters:
  DatabaseName:
    Default: mydb
    Type: String
  DatabasePassword:
    NoEcho: true
    Type: String
  DatabaseUsername:
    NoEcho: true
    Type: String
Resources:
  PostgresDatabase:
    Properties:
      AllocatedStorage: 100
      DBInstanceClass: db.t2.micro
      DBName:
        Ref: DatabaseName
      Engine: postgres
      Iops: 1000
      MasterUserPassword:
        Ref: DatabasePassword
      MasterUsername:
        Ref: DatabaseUsername
      PubliclyAccessible: true
    Type: AWS::RDS::DBInstance
